repos:
    - repo: local
      hooks:
          - id: ruff-format
            name: ruff-format
            entry: uv run ruff format
            language: system
            types: [python]
            args: []

          - id: ruff-lint
            name: ruff-lint
            entry: uv run ruff check
            language: system
            types: [python]
            args: []
